package com.github.aszecsei.crowtech.common.registries

import com.github.aszecsei.crowtech.common.materials.Material
import com.github.aszecsei.crowtech.common.materials.properties.*
import java.util.*

object MaterialRegistry {
    val MATERIALS = TreeMap<String, Material>()

    val IRON = Material("iron", "Iron")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.RAW_PROPERTY, RawProperty().doNotGenerate())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().doNotGenerate())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty().doNotGenerate())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xC8C8C8)
        .register()

    val COPPER = Material("copper", "Copper")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.RAW_PROPERTY, RawProperty().doNotGenerate())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().doNotGenerate())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xe77c56)
        .register()

    val GOLD = Material("gold", "Gold")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.RAW_PROPERTY, RawProperty().doNotGenerate())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().doNotGenerate())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty().doNotGenerate())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xFFE650)
        .register()

    val ALUMINUM = Material("aluminum", "Aluminum")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0x3fcaff)
        .register()

    val IRIDIUM = Material("iridium", "Iridium")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xe1e6f5)
        .register()

    val LEAD = Material("lead", "Lead")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0x6a76bc)
        .register()

    val NICKEL = Material("nickel", "Nickel")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xFAFAC8)
        .register()

    val OSMIUM = Material("osmium", "Osmium")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xFAFAC8)
        .register()

    val PLATINUM = Material("platinum", "Platinum")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xffe5ba)
        .register()

    val SILVER = Material("silver", "Silver")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().withTexture(IngotProperty.IngotTexture.SHINY))
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xDCDCFF)
        .register()

    val TIN = Material("tin", "Tin")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xc0bcd0)
        .register()

    val TITANIUM = Material("titanium", "Titanium")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xDCA0F0)
        .register()

    val TUNGSTEN = Material("tungsten", "Tungsten")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.DIAMOND))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0x8760ad)
        .register()

    val URANIUM = Material("uranium", "Uranium")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3).needs(OreProperty.ToolTierRequirement.IRON))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0x39e600)
        .register()

    val ZINC = Material("zinc", "Zinc")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().withMin(1).withMax(3))
        .set(MaterialProperty.RAW_PROPERTY, RawProperty())
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xDADAA8)
        .register()

    val BLACK_BRONZE = Material("black_bronze", "Black Bronze")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0x8b7c70)
        .register()

    val BRONZE = Material("bronze", "Bronze")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xffcc00)
        .register()

    val BRASS = Material("brass", "Brass")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().withTexture(IngotProperty.IngotTexture.SHINY))
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xffe36e)
        .register()

    val ELECTRUM = Material("electrum", "Electrum")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().withTexture(IngotProperty.IngotTexture.SHINY))
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xffff8b)
        .register()

    val INVAR = Material("invar", "Invar")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xe2e8e1)
        .register()

    val ROSE_GOLD = Material("rose_gold", "Rose Gold")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty().withTexture(IngotProperty.IngotTexture.SHINY))
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0xecd5b8)
        .register()

    val STEEL = Material("steel", "Steel")
        .set(MaterialProperty.INGOT_PROPERTY, IngotProperty())
        .set(MaterialProperty.NUGGET_PROPERTY, NuggetProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.ROD_PROPERTY, RodProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.WIRE_PROPERTY, WireProperty())
        .set(MaterialProperty.MEAN_RGB, 0x3f3f3f)
        .register()

    val DIAMOND = Material("diamond", "Diamond")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.GEM_PROPERTY, GemProperty().doNotGenerate())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.MEAN_RGB, 0xC8FFFF)
        .register()

    val EMERALD = Material("emerald", "Emerald")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.GEM_PROPERTY, GemProperty().doNotGenerate())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.MEAN_RGB, 0x17ff6c)
        .register()

    val LAPIS = Material("lapis", "Lapis")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.GEM_PROPERTY, GemProperty().doNotGenerate())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.MEAN_RGB, 0x2836f1)
        .register()

    val QUARTZ = Material("nether_quartz", "Nether Quartz")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty().doNotGenerate())
        .set(MaterialProperty.GEM_PROPERTY, GemProperty().doNotGenerate())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.MEAN_RGB, 0xf8efe3)
        .register()

    val RUBY = Material("ruby", "Ruby")
        .set(MaterialProperty.ORE_PROPERTY, OreProperty())
        .set(MaterialProperty.GEM_PROPERTY, GemProperty())
        .set(MaterialProperty.DUST_PROPERTY, DustProperty())
        .set(MaterialProperty.PLATE_PROPERTY, PlateProperty())
        .set(MaterialProperty.GEAR_PROPERTY, GearProperty())
        .set(MaterialProperty.MEAN_RGB, 0xd72310)
        .register()
}